### ISSUE TITLE
multiple producer issue found (and fixed)

### ISSUE THREAD

**Issue by pablogh-2000** [alexleemanfui/disruptor4cpp#1]
Hi,

just for anyone using this porting of the disruptor in C++11, including the author.
I have been using this otherwise excellent implementation and came across a bug when using it in multiple producer. There is a little big bug in this line:

https://github.com/alexleemanfui/disruptor4cpp/blob/master/include/disruptor4cpp/utils/util.h#L82

it should be:

```((value / 2 == 1) ? 1 : log2(value / 2) + 1)```
Notice the comparison to ```1``` instead of ```0```.

Thanks,

Pablo.

**Comment by alexleemanfui** [comment]
Fixed. Thanks Pablo!
